window.onload=(e)=>{let btgThum=document.querySelector("#btg-layout-thum");let btgList=document.querySelector("#btg-layout-list");let btgContentDiv=document.querySelector(".btg-content");if(btgThum){btgThum.addEventListener("click",(e)=>{console.log('Thum');if(btgThum.classList.contains("btg-layout-active")){return false;}
let btgActiveElm=document.querySelector(".btg-layout-active");btgActiveElm.classList.remove("btg-layout-active");btgThum.classList.add("btg-layout-active");btgContentDiv.classList.remove("btg-list");setCookie("layout","",{expires:-1,path:"/"});});btgList.addEventListener("click",(e)=>{console.log('List');if(btgList.classList.contains("btg-layout-active")){return false;}
let btgActiveElm=document.querySelector(".btg-layout-active");btgActiveElm.classList.remove("btg-layout-active");btgList.classList.add("btg-layout-active");btgContentDiv.classList.add("btg-list");setCookie("layout","true",{expires:604800,path:"/"});});}
let btgHrefStr=location.href;if(btgHrefStr.indexOf("prod")>=0&&getRandomInt(0,10)==7){ajax(myAjaxUrl,"POST","action=nopriv_add_rating&add_my_rating=true&product_id="+btgCurPostId).then(result=>{});}
let btgThumb=document.querySelector(".btg-post-thumb-wrap a");if(btgThumb){let btgLightBoxBackground=document.createElement("div");let btgLightBoxWrap=document.createElement("div");let btgLightBoxThumbWrap=document.createElement("div");let btgLightBoxThumb=document.createElement("img");let btgLightBoxThumbDescWrap=document.createElement("div");let btgLightBoxThumbDesc=document.createElement("p");let btgLightBoxCloseBtn=document.createElement("div");btgLightBoxThumbWrap.appendChild(btgLightBoxThumb);btgLightBoxThumbDescWrap.appendChild(btgLightBoxThumbDesc);btgLightBoxWrap.appendChild(btgLightBoxThumbWrap);btgLightBoxWrap.appendChild(btgLightBoxThumbDescWrap);btgLightBoxWrap.appendChild(btgLightBoxCloseBtn);btgLightBoxBackground.appendChild(btgLightBoxWrap);document.body.appendChild(btgLightBoxBackground);btgLightBoxCloseBtn.classList.add("btgCloseLiteBox");btgLightBoxThumbDescWrap.classList.add("btgLightBoxThumbDescWrap");btgLightBoxThumbWrap.classList.add("btgLightBoxThumbWrap");btgLightBoxWrap.classList.add("btgLightBoxWrap");btgLightBoxBackground.classList.add("btgLightBoxBackground");btgLightBoxThumb.src=btgThumb.href;btgLightBoxThumb.alt=btgThumb.querySelector("img").alt;btgLightBoxThumbDesc.innerText=btgThumb.querySelector("img").alt;btgLightBoxCloseBtn.innerText="+";btgLightBoxWrap.addEventListener("click",(e)=>{e.stopPropagation();});btgThumb.addEventListener("click",(e)=>{e.preventDefault();btgShowLightBox(btgLightBoxBackground);});btgLightBoxCloseBtn.addEventListener("click",(e)=>{btgHideLightBox(btgLightBoxBackground);});btgLightBoxBackground.addEventListener("click",(e)=>{btgHideLightBox(btgLightBoxBackground);});}}
function btgShowLightBox(btgLightBoxBackground){btgLightBoxBackground.style="display: block;";let btgTansitionTime=setTimeout(()=>{btgLightBoxBackground.classList.add("btgShowEvent");},1);}
function btgHideLightBox(btgLightBoxBackground){btgLightBoxBackground.classList.remove("btgShowEvent");let btgTansitionTime=setTimeout(()=>{btgLightBoxBackground.style="display: none;";},200);}
function setCookie(name,value,options){options=options||{};let expires=options.expires;if(typeof expires=="number"&&expires){let d=new Date();d.setTime(d.getTime()+expires*1000);expires=options.expires=d;}
if(expires&&expires.toUTCString){options.expires=expires.toUTCString();}
value=encodeURIComponent(value);let updatedCookie=name+"="+value;for(let propName in options){updatedCookie+="; "+propName;let propValue=options[propName];if(propValue!==true){updatedCookie+="="+propValue;}}
document.cookie=updatedCookie;}
function getRandomInt(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function ajax(url,method,data){return new Promise((resolve,reject)=>{var request=new XMLHttpRequest();request.responseType='text';request.onreadystatechange=function(){if(request.readyState===XMLHttpRequest.DONE){if(request.status===200){resolve(request.responseText);}else{reject(Error(request.statusText));}}};request.onerror=function(){reject(Error("Network Error"));};request.open(method,url,true);request.setRequestHeader("Content-type","application/x-www-form-urlencoded");request.send(data);});}